inc/lock.class.php

fix http://forge.fusioninventory.org/issues/2864

locks bugs

---

ajax/expand_task.php
css/views.css
inc/task.class.php
inc/task.view.class.php
js/taskjobs.js

proposal for http://forge.fusioninventory.org/issues/2901

0.85/collapse tasks in monitoring / logs

---

inc/unmanaged.class.php

Fix for sysdesc textarea

---

inc/ignoredimportdevice.class.php
inc/menu.class.php
inc/profile.class.php

Conflicts:
inc/profile.class.php

create specific right for view ignoredimportdevices

---

inc/inventorycomputerlib.class.php

With a big xml (1.1Mo, ~3000 softwares), parsing time (on new insertion) : from ~30-40s to 2s

optimise softwares loading (more than 15x)

---

.travis.yml

Try fix php versions in phpunit / travis
Fix travis fatal error

Add php7 to travis

---

front/iprange.form.php
inc/iprange.class.php
install/update.php
phpunit/1_Unit/DeleteLinkedObjectsTest.php

Fix delete snmp community of iprange
Fix delete iprange
FIx delete and add code to clean on update plugin

Delete iprange_snmpcommunity when delete iprange. references #1774

---

b/deploy/index.php
inc/communicationnetworkinventory.class.php
inc/formatconvert.class.php
inc/inventorycomputerinventory.class.php
inc/lock.class.php
phpunit/1_Unit/ComputerLogTest.php
phpunit/1_Unit/ComputerUpdateTest.php
phpunit/1_Unit/FormatConvertDataTest.php
phpunit/1_Unit/VirtualmachineTest.php
phpunit/2_Integration/ComputerLocksTest.php

Try fix tests
Fix unit test
Fix unit test for lock
Try not to import dropdown values when the field is locked
Try fix unit tests
Fix locks
Fix locks
FIx test for locks
Try fix locks
Fix locks
Add test for itemtype lock
Fix call replaceids function with new arguments
Fix locks tests

Add unit test for locks. closes #1766

---

phpunit/1_Unit/ComputerLogTest.php
phpunit/1_Unit/ComputerUpdateTest.php
phpunit/1_Unit/NetworkEquipmentUpdateDiscoveryTest.php
phpunit/1_Unit/NetworkEquipmentUpdateTest.php
phpunit/1_Unit/PrinterUpdateTest.php
phpunit/1_Unit/VirtualmachineTest.php
phpunit/2_Integration/UnmanagedImportTest.php

Depends on https://github.com/glpi-project/glpi/pull/667 and https://github.com/glpi-project/glpi/pull/668

Fix unittests

---

inc/networkequipment.class.php
inc/statediscovery.class.php

Default date values are now null in database; those checks will no longer work as expected

Dates are no longer 000-00-00 per default

---

inc/formatconvert.class.php
inc/inventorycomputerlib.class.php

This PR replace #1795 ; code is the same, but has been moved according to david comment :)

Add hooks to import data from plugins

---

.travis.yml
hook.php
inc/computeroperatingsystem.class.php
inc/formatconvert.class.php
inc/inventorycomputerlib.class.php
inc/ruledictionnarycomputerarch.class.php
install/mysql/plugin_fusioninventory-empty.sql
install/update.php
phpunit/1_Unit/ComputerTransformationTest.php

Use core's architectures table instead of specific fusion one.
Also remove specific table; and take care of updating data.

Use core's architectures tables

---

inc/config.class.php
inc/formatconvert.class.php
inc/inventorycomputerlib.class.php
install/update.php
phpunit/1_Unit/ComputerTransformationTest.php

Import operating system informations in GLPi core,
Add a parameter to manage or not operating system name (not managed => verbatim OS name sent by the agent).
This PR contains commit from #1928 since this is required to use and populate core's architecture tables  in order to get them available from computer; but they're two diffrent things, so I've created two different PR's  :)

9.1/core os infos

---

index.php

Fix redirect (#1926)

---

phpunit/0_Install/GLPIInstallTest.php
scripts/cli_install.php
setup.php

Enhance error text when not have compatible GLPI version.
Add error to deny install witj cli_install script if GLPI version not compatible.

Update test tu use glpi 9.1.1 database.

---

fusioninventory.xml

To keep plugins website up-to-date ;)

Update XML file with latest releases

---

inc/deployaction.class.php
inc/deployfile.class.php

Fix checkbox and number
closes #1966

Fix delete deploy package

---

inc/agentwakeup.class.php
inc/task.class.php
inc/task.view.class.php
install/mysql/plugin_fusioninventory-empty.sql
install/update.tasks.php

Separate timeslot usage in task into two:
- preparation
- execution

separe timeslot in task into 2 fields (preparation & execution)

---

install/update.php

fix update of dynamic group data

---

inc/collectrule.class.php

Tested on my server and it is running ok

Fix #2026 - allow to use regex result for location and state

---

phpunit/2_Integration/ComputerHistoryTest.php

- Added a short xml for linux
- Changed bsd xml (adding some softwares)
- split into two functions

add a check for linux inventory and softwares logs

---

inc/agent.class.php

Do not instanciate again object

---

front/send.php
install/update.php

Drop usage of removed core methods

Die magic_quotes, die!

---

front/config.form.php

Fix display of configuration form

---

front/menu.php

Refresh plugin's homepage.
This is controlled by the user's preferences to refresh tickets list.

Add code to refresh the plugin's homepage

---

inc/config.class.php
inc/unmanaged.class.php

See https://github.com/glpi-project/glpi/issues/807

Rename isActive to isFieldActive

---

inc/deployaction.class.php
inc/deploycheck.class.php
inc/deployfile.class.php
inc/deploypackage.class.php

lock package when running task present

---

inc/configsecurity.class.php
inc/configuration.class.php
inc/networkequipment.class.php
inc/networkportlog.class.php
inc/printerlog.class.php
inc/search.class.php
phpunit/0_Install/FusinvDB.php
report/ports_date_connections.php

Fix 9.2 compat

---

inc/formatconvert.class.php
phpunit/1_Unit/FormatConvertDataTest.php
phpunit/custom-build.xml

Rework drive device detection method.
Also add unit tests for it.

Improve drive devices detection

---

css/views.css
inc/deploypackage.class.php
setup.php

enhance self-deploy (add css, logs, and restart)

---

inc/deploypackage.class.php
phpunit/2_Integration/Deploy/PackageSelfDeployTest.php

Filter the list of packages to deploy by entity.

Take care or entity for on demand packages

---

inc/formatconvert.class.php

See https://github.com/fusioninventory/fusioninventory-agent/issues/319

Fix memory frequency

---

inc/inventoryprinterlib.class.php
inc/printer.class.php
phpunit/1_Unit/PrinterUpdateTest.php

Update GLPI last page counter when fusioninventory performs a remote SNMP inventory

 Store global counter of printer in GLPI core closes #678

---

phpunit/0_Install/GLPIInstallTest.php
setup.php

Following changes on GLPI version (now "9.2-dev").

Make plugin  dev compatibe with GLPI dev

---

inc/menu.class.php

Do not propose to help for translating version 0.84 but 9.2 instead

Update transifex resource to help for translation

---

inc/deploycheck.class.php
phpunit/1_Unit/Deploy/DeploycheckTest.php

To go along with https://github.com/fusioninventory/fusioninventory-agent/pull/331 
Add a new audit to check if the value of registry is not equals to something

Add unit tests

---

front/printerlogreport.php
inc/printerlog.class.php
report/ports_date_connections.php

Html::showDateFormItem has been removed in GLPI 9.2
Replace showDateFormItem by showDateField

Replace Html::showDateFormItem by Html::showDateField

---

inc/collect.class.php
inc/collect_file_content.class.php
inc/collect_registry_content.class.php
inc/collect_wmi_content.class.php
setup.php

Merge the content of the 3 collect tabs in one

Merge content infos in one single tab

---

inc/formatconvert.class.php
phpunit/1_Unit/VirtualmachineTest.php

Import VM comments

---

inc/inventorycomputerlib.class.php
install/update.php
phpunit/1_Unit/ComputerUpdateTest.php

See https://github.com/glpi-project/glpi/issues/2630 (https://github.com/glpi-project/glpi/pull/2671 must be merged first).

Handle OS is_dynamic and entities_id

---

install/install.php
install/update.php

Plugin  installation fails when GLPI is set to French, as example

Translated comments may contain characters that make the query fail

---

inc/taskview.class.php

If we encode the value "1", we'll get "'1'"

Drop unseless json_encode; fixes #2194

---

inc/inventorycomputerlib.class.php

As I cannot reproduce... This is currently tested.

Try to fix duplicate entries on OS on some cases

---

inc/deploycheck.class.php
phpunit/1_Unit/Deploy/DeploycheckTest.php

Theses checks are present in agent since years

add missing directory checks

---

hook.php
inc/communicationnetworkdiscovery.class.php
inc/configsecurity.class.php
inc/iprange.class.php
inc/iprange_configsecurity.class.php
inc/menu.class.php
inc/networkequipment.class.php
inc/printer.class.php
inc/profile.class.php
inc/unmanaged.class.php
report/not_queried_recently.php
scripts/import_ip_ranges.php

An identifier/password combination constitute a set of credentials, not an authentication.

turn 'SNMP authentication' in 'SNMP credentials'

---

inc/inventorycomputerlib.class.php

fix theses warnings:
```
*** PHP Warning(2): A non-numeric value encountered
Backtrace :
...nventory/inc/inventorycomputerlib.class.php:406
...ry/inc/inventorycomputerinventory.class.php:577 PluginFusioninventoryInventoryComputerLib->updateComputer()
...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
inc/rulecollection.class.php:1461                  Rule->process()
...ry/inc/inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
...ry/inc/inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
...fusioninventory/inc/communication.class.php:235 …
```

cast memories frequency to avoid warning on comparison

---

hook.php

Only in subentities
> PHP Notice: Undefined index: name in /glpi/appli/glpi/plugins/fusioninventory/hook.php at line 752

prevent notices in ignoredimportedevice

---

ajax/deploy_displaytypevalue.php

File upload form doesn't appear because of wrong class file check

Fix package upload form display

---

inc/formatconvert.class.php
inc/inventorycomputerlib.class.php

Fix undefined variables

---

inc/formatconvert.class.php
inc/inventorycomputerlib.class.php
phpunit/1_Unit/SoftwareUpdateTest.php
phpunit/custom-build.xml

Add comments for software import to be more readable
Factorize code

Factorize software import

---

inc/inventorycomputerlib.class.php

Fix tests: insert null and not 'NULL' in date_creation.
Use contant instead of hardcoded software string separator

Fix date install

---

inc/inventorycomputerinventory.class.php

fix indentation

---

inc/task.class.php
inc/taskjobview.class.php
inc/toolbox.class.php

Fix #2403: only one job per task
Fix #2404: correctly target a task with computers massive actions

Tasks jobs management

---

front/deploygroup.form.php
inc/deploygroup_staticdata.class.php
phpunit/1_Unit/Deploy/DeploygroupTest.php
phpunit/1_Unit/Deploy/computers.csv

Rebase on 9.2 branch + fix comments of @wawax on #2216

Add csv import feature for static deploy groups

---

inc/formatconvert.class.php
inc/inventorycomputercomputer.class.php
inc/item.class.php
inc/networkequipment.class.php
inc/printer.class.php
inc/rulematchedlog.class.php
inc/toolbox.class.php
install/install.php
install/update.php

Factorize code to display FI infos on assets
Rename XML files stored on the filesystem : add a .xml suffix
Add a download XML function for network equipments and printers

Download xml file & change name of the file

---

tools/setup_snmp_inventory.php

This script quiclky creates : 
- an IP range
- an SNMP authentication
- add the SNMP auth to the IP range
- add an agent and a computer
- create a discovery task
- create an snmp inventory task

Add a script to quiclky setup a SNMP discovery/inventory environment

---

inc/networkequipment.class.php

Couldn't find a way to do the job with just SQL, so i brought PHP to help.

Naturally sort network ports

---

inc/agent.class.php
inc/computer.class.php
inc/credential.class.php
inc/credentialip.class.php
inc/deploygroup.class.php
inc/deploymirror.class.php
inc/deploypackage.class.php
inc/ignoredimportdevice.class.php
inc/inventorycomputerblacklist.class.php
inc/iprange.class.php
inc/networkport.class.php
inc/printerlog.class.php
inc/printerlogreport.class.php
inc/task.class.php
inc/taskjob.class.php
inc/taskjoblog.class.php
inc/timeslot.class.php
inc/timeslotentry.class.php
inc/unmanaged.class.php
install/update.php

Hello,
This update removes the exception throw by GLPI with the searchOption function and follows their standards code.
Closes #2543

Update deprecated function call

---

.travis.yml
RoboFile.php
css/views.css
front/deploygroup.form.php
inc/collectrule.class.php
inc/deploycommon.class.php
inc/deploygroup_dynamicdata.class.php
inc/inventorycomputerlib.class.php
inc/inventorynetworkequipmentlib.class.php
inc/inventoryruleentity.class.php
inc/inventoryruleimport.class.php
inc/inventoryrulelocation.class.php
inc/networkequipment.class.php
inc/printerlogreport.class.php
inc/task.class.php
install/install.php
install/update.php
phpunit/1_Unit/Deploy/DeployactionTest.php
phpunit/1_Unit/PrinterUpdateTest.php
phpunit/2_Integration/CollectRuleTest.php
tools/setup_snmp_inventory.php

Fix update

---

inc/menu.class.php
inc/task.class.php
inc/toolbox.class.php
phpunit/2_Integration/Tasks/CronTaskTest.php

linked with  #2518 sur on _master_ branch

Closes #2412 - improve the get jobs log process

---

inc/formatconvert.class.php

Related to https://github.com/glpi-project/glpi/pull/3585

Add code to manage LDAP domain when search the computer user in GLPI DB

---

install/mysql/oui.sql
install/mysql/pciid.sql
install/mysql/plugin_fusioninventory-empty.sql
install/mysql/usbid.sql
install/update.php
phpunit/1_Unit/Deploy/PackageJsonTest.php
tools/datafilter/FilesToDB.php

Switch to innodb

---

setup.php

Too much hassle when patching min and max GLPI versions requirements. Adding constants

WIP Use constants for GLPI min and max version

---

inc/formatconvert.class.php
phpunit/1_Unit/SoftwareUpdateTest.php

Add COMMENTS support to softwares inventory

---

inc/communication.class.php
phpunit/Common_TestCase.php

I'm not very confident with the impact of this.
But the rights injection in glpi session is clearly bad.
Fix: #2357, #2596, #2623

use correct glpi rights to import xml

---

.travis.yml
phpunit/1_Unit/ComputerUpdateTest.php
phpunit/bootstrap.php
phpunit/composer.json
phpunit/testsuites_install.xml
phpunit/testsuites_integration.xml
phpunit/testsuites_unit.xml
phpunit/testsuites_update.xml

Update phpunit from version 6 to version 7

Fix fatal error with diff class when assertEquals not same.

---

setup.php

And this breaks at least one PR to come on GLPI master branch.

 This is not needed here; done GLPI side

---

inc/printerlog.class.php

Tiny fix for #2768

---

inc/agent.class.php

Fix ecmascript compat

---

inc/formatconvert.class.php
inc/inventorycomputerlib.class.php

-> https://github.com/glpi-project/glpi/pull/5337
Recover new data for disks : 
- ENCRYPT_NAME
- ENCRYPT_ALGO
- ENCRYPT_STATUS
- ENCRYPT_TYPE

Encrypted volumes

---

inc/lock.class.php

1. Field list was displayed twice.
2. As call to `PluginFusioninventoryLock::setLockArray()` was not returning anything, result was always considered as failure here: https://github.com/fusioninventory/fusioninventory-for-glpi/blob/glpi9.4/inc/lock.class.php#L945.
Should fix #2743

Fix (un)lock massive action

---

inc/computerremotemanagement.class.php

start teamviewer connection directly from glpi computer interface
https://start.teamviewer.com/id directly connects to the id with the local installed teamviewer client.
this is my very first pr, i hope everything is fine :)

teamviewer id clickable

---

inc/formatconvert.class.php
inc/inventorynetworkequipmentlib.class.php

Take in charge Tagged Vlan from XML
cf. https://github.com/fusioninventory/fusioninventory.github.io/pull/66
https://github.com/fusioninventory/fusioninventory-agent/pull/708

Tagged Vlan

---

hook.php

Solve [GLPI 9.4.4] Search doesn't work

---

inc/agent.class.php
inc/collect.class.php
inc/collectcommon.class.php
inc/configsecurity.class.php
inc/deploygroup.class.php
inc/deploymirror.class.php
inc/deploypackage.class.php
inc/inventorycomputerblacklist.class.php
inc/iprange.class.php
inc/taskjobview.class.php
inc/taskview.class.php
inc/unmanaged.class.php

Required to enable autocomplete on GLPI 9.4.4+ (see https://github.com/glpi-project/glpi/commit/339b856273f2cf5cb409e6db1a2689a418c5a051)

Whitelist autocomplete fields

---

inc/lock.class.php

On manually item update load general lock to prevent clear or update values
see #2946 
Best regards

Load general lock on manually item update

---

.travis.yml
inc/lock.class.php
install/update.php

Fix 94 php74

---

setup.php

fix(core): fix networkport view

---

b/collect/index.php

Empty file with a "0" size are now supported for the Collect task.
Also the error forced the server to return a wrong page but it would be better to at least return the CRSF token.

Collect fixes

---

inc/computer.class.php

Added check to test if Fields plugin is installed through the marketplace, so installed in marketplace folder not plugins folder.
If so include hook.php from marketplace path instead of plugins path.
#3013

Fix for issue #3013 : Added check if Fields plugin is installed through the marketplace

---

hook.php
inc/agent.class.php
inc/collectrule.class.php
inc/credential.class.php
inc/credentialip.class.php
inc/deploymirror.class.php
inc/deploypackage.class.php
inc/entity.class.php
inc/ignoredimportdevice.class.php
inc/inventorycomputercomputer.class.php
inc/inventoryruleentity.class.php
inc/inventoryruleimport.class.php
inc/inventoryrulelocation.class.php
inc/iprange.class.php
inc/networkportconnectionlog.class.php
inc/networkportlog.class.php
inc/printerlog.class.php
inc/rulematchedlog.class.php
inc/task.class.php
inc/taskjob.class.php
inc/taskjoblog.class.php
inc/taskjobstate.class.php
inc/timeslot.class.php
inc/timeslotentry.class.php
inc/unmanaged.class.php

Fix wrong locales singular/plurals

---

inc/config.class.php

Fix typo equipment

---

inc/formatconvert.class.php
inc/inventorycomputerlib.class.php
phpunit/1_Unit/ComputerTransformationTest.php
phpunit/2_Integration/ComputerDeviceBatteryTest.php

see 
incomplete spec  for JSON format
https://github.com/glpi-project/inventory_format/pull/18
XML spec 
https://github.com/fusioninventory/fusioninventory.github.io/pull/75
Bad value collected by the agent
https://github.com/fusioninventory/fusioninventory-agent/issues/840
https://github.com/fusioninventory/fusioninventory-agent/pull/843
support for current max capacity to monitor battery wear
https://github.com/glpi-project/glpi/pull/8062

Fix battery handling

---

inc/config.class.php
inc/formatconvert.class.php
inc/inventorycomputerlib.class.php
install/update.php
phpunit/0_Install/mysql/i-2.3.3.sql
phpunit/1_Unit/ComputerLogTest.php
phpunit/1_Unit/ComputerTransformationTest.php
phpunit/1_Unit/ComputerUpdateTest.php
phpunit/1_Unit/VirtualmachineTest.php
phpunit/2_Integration/ComputerAntivirusTest.php
phpunit/2_Integration/ComputerDeviceBatteryTest.php
phpunit/2_Integration/ComputerDeviceSimcardTest.php
phpunit/2_Integration/ComputerDynamicTest.php
phpunit/2_Integration/ComputerLicenseTest.php
phpunit/2_Integration/ComputerMonitorTest.php
phpunit/2_Integration/DevicesLocksTest.php
phpunit/2_Integration/UnmanagedManagedTest.php

Power supplies
