fusioninventory/fusioninventory-for-glpi

hook.php
When adding this fields in display preferences of Printer page ( global or personnal) : 
* snmp authentication
* fusinv - last inventory
, we got a sql error : 
/* Erreur SQL (1066): Not unique table/alias: 'glpi_plugin_fusioninventory_printers' */
The commit attached fixes this issue.
However, I can't understand the reason of presence of array_pop on already_linked_tables var.
Maybe an old code from previous glpi version.
Also, I could fix this issue by using join_param on the searchoption (with before_join) and remove the corresponding hooks.
Did you have a constraint to declare these joins (all) in plugin_fusioninventory_addLeftJoin function (hook.php) ?
Rgds.
=> Double join in printer when adding colums in display preferences

inc/task.class.php, phpunit/2_Integration/Tasks/DeleteTest.php
Dans le cas de tâches régulières et fréquentes (ex : déploiement toutes les 10 min sur un ensemble de serveurs assez conséquent), le nombre de jobslogs, states et jobs augmente considérablement et le temps de suppression explose au choix le timeout du serveur ou le max de ram allouée à php.
Je n'ai pas trouvé l’intérêt de supprimer en cascade via les fonctions delete() de chaque objets et de plus en cascade. L'historique n'est jamais affiché pour ces sous-objets.   
Un delete sql comme proposé ici s'exécute en moins de 2s pour le même résultat.   
Merci par avance.
=> Performance de la suppression des tâches

inc/formatconvert.class.php
When a proxy is used to contact GLPI, `$_SERVER['REMOTE_ADDR']` may not contains the agent's IP address. The true IP can be in "_X-Forwarded-For_" or "_X-Real-IP_" HTTP headers (depends on proxy's configuration).
This pull request aims to make fusioninventory-for-glpi able to deal with both cases (_proxyfied_ requests and _no-proxyfied_ ones) to determine the "_Public contact address_".
=> Adds attempts for proxy-related HTTP headers to determine contact IP address

inc/computer.class.php
In static groups, when we remove a computer from associated item, we had a message "Failed operation"
=> fix ok message on remove item from static group

inc/formatconvert.class.php, phpunit/1_Unit/ComputerTransformationTest.php, phpunit/1_Unit/ComputerUpdateTest.php, phpunit/2_Integration/ComputerMonitorTest.php, phpunit/2_Integration/ComputerPeripheralTest.php, phpunit/2_Integration/ComputerPrinterTest.php
Add tests for is_dynamic fix
Fix unit test
Fix is_dynamic printer
FIx phpunit with is_dynamic and printers
Fix unit tests
=> Add is_dynamic=1 when importing a monitor or a peripheral or printer

phpunit/build.xml
There is an hardcoded http host and port hard coded in CollectsTest.php file; that prevents unit tests to be run on my local machine.
I've tried to add a parameter at runtime; I do not know if there is another way to go, I do not know much ant nor phpunit, and I'm not sure of the possible interactions between both of them.
Well, that works for me, but maybe there would be a more simple or elegant  solution.
=> Add a build parameter to replace hardcoded http host in CollectsTest.php

hook.php, inc/collect_file_content.class.php, inc/collect_registry_content.class.php, inc/collect_wmi_content.class.php, inc/computerlicenseinfo.class.php, inc/lock.class.php, phpunit/2_Integration/CollectsTest.php, phpunit/2_Integration/ComputerLicenseTest.php
Clean locks and rules when an asset is purged.
Replaces #1755, to add requested unit tests.
=>  Delete locks and matches rule logs when an asset is purged

inc/agent.class.php, inc/inventorycomputerinventory.class.php, inc/inventoryruleimport.class.php
Add a new rule import criterion to check for a computer using the agent's device id.
It helps to linked a computer when the serial and/or uuid is missing or wrong
=> add link criterion : device_id

scripts/cli_install.php
Hi
The unit tests of GLPI provide an argument --tests which alters the directory of config_db.php. This is very convenient to unit test GLPI (and plugins) in a database different than the database I use for development (and contaning my data set).
I implemented a cli installer for a few plugins I maintain with this feature for months and fount it really convenient.
This PR give the same feature to FusionInventory.
Install GLPI in unit test context 
```php tools/cliinstall.php --db=database --user=glpi --pass=glpi --tests```
then install FusionIvnentory 
```php scripts/cli_install.php --tests```
and install other plugins and run its unit tests (for my needs).
I think this PR would be benefit FusionInventory too as it uses its own cli installer to install and unit test the database schema. …
=> allow install of FusionInventory from CLI using the test context of GLPI

setup.php
This code seems old and not usefull for current version.
Also, it induce some very strange behaviors detected on a replicated glpi instance (lock present on slave, some tables unavailable) and a reset of link rules.
=> drop old checks for 0.84 version

inc/ignoredimportdevice.class.php, inc/inventorycomputerinventory.class.php, install/mysql/plugin_fusioninventory-empty.sql, install/update.php, phpunit/2_Integration/RuleIgnoredImportTest.php
A description:
- add a new key into glpi_plugin_fusioninventory_ignoredimportdevices table for agents_id
- add a new searchoption corresponding to this key
- update existing ignored import device row when a similar entry exist (instead of always adding it)
- minor: [remove a duplicate in a searchoption of this class](https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2044/files#diff-c745a6385b9b7ba9fc4e5e79f0e78c41L116)
=> Link agent into ignoredimportdevice

front/agent.form.php, inc/agent.class.php, phpunit/1_Unit/AgentTest.php
When disconnecting an agent from a computer, remove agent related information in fusioninventory tables.
Do not also display the FusionInventory Agent tab is not agent linked to a computer.
=> Disconnect agent

inc/lock.class.php
This impacts the retrieval of inventory data when deleting locks.
If after deletion of a lock, another locks are still present, it works as intended (update case)
But in case of deletion of all lock (or last lock), deletion is ok but retrieval of data not triggered (delete case).
This fix, check the presence of item->update in deletelock function to detect if a CommonDBTM::delete or update function is triggered.
=> retrieve inventory data in case of delete last lock on a item

hook.php, inc/formatconvert.class.php, install/mysql/plugin_fusioninventory-empty.sql, install/update.php, phpunit/1_Unit/ComputerUpdateTest.php
Retrieve and display computers hostid.
This information may be used by software vendors for licensing purpose.
=> Add computer's hostid as the agent now retrieves it

inc/config.class.php, inc/formatconvert.class.php, phpunit/2_Integration/RemovableMediaImportTest.json, phpunit/2_Integration/RemovableMediaImportTest.php
This patch allow import of removable volumes, previously filtered out.
Code commented out because I think it may be useful to build an admin preference in the plugin's settings panel.
=> enable import of removable media

.travis.yml, ajax/deploypackage_form.php, front/deploypackage.public.php, inc/config.class.php, inc/deploypackage.class.php, inc/menu.class.php, inc/profile.class.php, inc/task.class.php, inc/task.view.class.php, install/install.php, install/mysql/plugin_fusioninventory-empty.sql, install/update.php, phpunit/0_Install/FusinvDB.php, phpunit/1_Unit/Tasks/TaskTest.php, phpunit/2_Integration/Deploy/PackageSelfDeployTest.php, phpunit/custom-build.xml
Ability to deploy packages on demand, not only for a self service person.
Add informations about packages available and being installed in the task tab of a computer.
Also add the possiblity, when user is using the standard interface to select if wakeup should be local (calling the agent as 127.0.0.1) or remote, from the server.
=> Deploy by tech

.travis.yml
Fix regression added in https://github.com/fusioninventory/fusioninventory-for-glpi/commit/e09b6d6
The glpi default branch is now 9.1/bugfixes and with the shallow clone (--depth=10), we don't have other branches available.
So i added '-b' option to directly precise the branch
=> clone with branch

inc/taskjobview.class.php
Current master only
added by this previous commit: 
https://github.com/fusioninventory/fusioninventory-for-glpi/commit/7783926dc67d2170832917854244394a7f5399e8#diff-7fd1588c26666307b62d6d529d8f01aaR837
the notice:
```
*** PHP Notice(8): Undefined index: id
Backtrace :
...s/fusioninventory/inc/taskjobview.class.php:503 
...s/fusioninventory/inc/taskjobview.class.php:173 PluginFusioninventoryTaskjobView->showForm()
plugins/fusioninventory/ajax/taskjob_form.php:65   PluginFusioninventoryTaskjobView->ajaxGetForm()
```
=> don't append edit_job on redirect if id is null, fix a notice

inc/deploygroup.class.php, inc/deploygroup_dynamicdata.class.php, inc/task.class.php, install/mysql/plugin_fusioninventory-empty.sql, install/update.php
When demanding a b/collect/index.php?action=getJobs , 
All agent are computed again and so a dynamic group listing launch.
Depending on the criteria saved in this group, query could be very long and executed again for **each** agent of this group (imagine a deployment for 1000 computers querying the dynamic group each). 
If i understand well, the code check if an agent always belongs to a prepared job and cancel if not.
For mass deployment, it's pretty aggressive on the server.
I suggest, in this pr, to cache computers_id of dynamic groups at the preparation of the task (use_cache = false, the default), and at the moment of execution, use this cache (use_cache = true).
Maybe, we can do better for this problem, but i don't see atm.
Also cleaned some incoherence in update.php
=> use cache on dynamic group

inc/formatconvert.class.php, phpunit/1_Unit/ComputerTransformationTest.php
This is to fix issue spotted in #2102; but not only.
Setting `['Computer']['operatingsystem{XYZ}']` to 0 would cause issues elsewhere, since this reference is still used (see for example ESX detection a few lines below OS stuff in Formatconvert class).
=> Previous OS stuff are still used; fixes #2102

inc/deploycheck.class.php, phpunit/1_Unit/Deploy/DeploycheckTest.php
Value is not well saved in database for an deployment audit value.
For example 9.20 will be stored in the JSON array as 9.2
=> Fix value interpretation in deploy audits

ajax/deploydropdown_operatingsystems.php, inc/config.class.php, inc/lock.class.php, install/update.php, scripts/cli_install.php, setup.php
Methods TableExists and FieldExists are deprecated in GLPI 9.2, breaking FI unit tests.
=> Remove calls to deprecate TableExists and FieldExists

inc/networkinventory.class.php
The task scheduler prepares a new jobstate at the each. Because of that, jobstate & joblogs tables are groing very fast
=> Avoid repreparing network inventory job at each taskscheduler run

inc/deploymirror.class.php, install/update.php, phpunit/0_Install/FusinvDB.php, phpunit/0_Install/FusinvUpdateTest.php
Enable existing mirror by default during migration.
Add search options for deploymirror.is_active
=> Deploymirror migration and searchoption

inc/timeslotentry.class.php
when displaying a timeslot form: 
```log
2017-10-20 09:37:43 [2@LU002]
*** MySQL query error:
SQL: SELECT * FROM `glpi_plugin_fusioninventory_timeslotentries` WHERE `plugin_fusioninventory_timeslots_id`=\'1\' ORDER BY `day`,
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
Backtrace :
inc/dbmysqliterator.class.php:264                  
inc/dbmysql.class.php:540                          DBmysqlIterator->__construct()
inc/dbutils.class.php:441                          DBmysql->request()
inc/db.function.php:270                            DbUtils->getAllDataFromTable()
...fusioninventory/inc/timeslotentry.class.php:194 getAllDatasFromTable() …
```
=> fix warning in timeslot form

hook.php
=> purge agent on computer purge when no task associated

inc/inventorycomputerlib.class.php
Actually, the missing serial in $arraydb causes a lot of log in php_errors.log
Ex on 0.85 (already seen in recent versions):
```
*** PHP Notice(8): Undefined index: serial
Backtrace :
...nventory/inc/inventorycomputerlib.class.php:347
...ry/inc/inventorycomputerinventory.class.php:566 PluginFusioninventoryInventoryComputerLib->updateComputer()
...inventory/inc/inventoryruleimport.class.php:719 PluginFusioninventoryInventoryComputerInventory->rulepassed()
inc/rule.class.php:1402                            PluginFusioninventoryInventoryRuleImport->executeActions()
inc/rulecollection.class.php:1455                  Rule->process()
...ry/inc/inventorycomputerinventory.class.php:369 RuleCollection->processAllRules()
...ry/inc/inventorycomputerinventory.class.php:108 …
```
=> avoid importing disks with empty serial

inc/timeslotentry.class.php
Case:
- timeslot entries is_recursive = no and its timeslot parent have is_recursive = yes
- global entity selector set to another entity than entries one:
Without patch:
---
With (note the absence of delete buttons):
=> prevent timeslot display when failing to check entities

inc/inventorycomputercomputer.class.php
=> inventory infos should not be displayed on computer creation (id <= 0)

inc/inventorycomputerlib.class.php, inc/toolbox.class.php
fix #2286
Also added a test in addDefaultStateIfNeeded to prevent set of states_id when defaut equals to 0
=> default states_id should not erase locked states_id

inc/inventorycomputerlib.class.php
fix the notice present when name is locked (and does not exist in ``$a_computerinventory``)
``$computerName`` is used only for construct history
```log
2017-11-09 09:11:17 [27@LU002]
*** PHP Notice(8): Undefined index: name
Backtrace :
...nventory/inc/inventorycomputerlib.class.php:187 
...ry/inc/inventorycomputerinventory.class.php:577 PluginFusioninventoryInventoryComputerLib->updateComputer()
...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
inc/rulecollection.class.php:1461                  Rule->process()
...ry/inc/inventorycomputerinventory.class.php:378 RuleCollection->processAllRules() …
```
=> prevent notice when lock set on name

inc/collect.class.php
I dropped some parts of collect which delete old content because:
- it deletes all data (also for others computers)
- it's redundant with another parts of code (ex for registry: https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/inc/collect_registry_content.class.php#L177)
For files collect, the [updateComputer](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/inc/collect_file_content.class.php#L149-L159) part doesn't have the deletion process, so i kept the query, but i added the filter on computers_id to avoid data deletion for others computers
=> run collect shouldnt delete old content for other agents

inc/computerlicenseinfo.class.php
Ex in xml:
```xml
<COMPONENTS>Access/AccessRuntime/Excel/ExcelConsumer/Groove/InfoPath/OneNote/Outlook/OutlookStandard/PowerPoint/Project/Publisher/SharePointDesigner/Visio/VisioSDK/Word/WordConsumer</COMPONENTS>
<FULLNAME>Microsoft Office Professionnel 2010</FULLNAME>
<KEY>...</KEY>
<NAME>Microsoft Office</NAME>
<OEM>1</OEM>
<PRODUCTID>...</PRODUCTID>
<TRIAL>0</TRIAL>
</LICENSEINFOS>
```
=> display licence fullname if not empty

ajax/remote_status.php, css/views.css, front/agent.form.php, inc/agent.class.php, inc/inventorycomputercomputer.class.php, setup.php
Status is called by ajax, so the computer page can't stuck.
I change showInfoForComputer prototype to pass Computer object needed by ``showRemoteStatus`` method
screenshot:
=> remove agent tab in computer, and get agent status in auto_inventory block

inc/inventorycomputerlib.class.php
500MB of logs in one night :D
here is an extract:
```
2017-11-23 09:23:49 [17134@wgpi1]
*** PHP Notice(8): Undefined index: name
Backtrace :
...nventory/inc/inventorycomputerlib.class.php:188
...ry/inc/inventorycomputerinventory.class.php:573 PluginFusioninventoryInventoryComputerLib->updateComputer()
...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
inc/rulecollection.class.php:1461                  Rule->process()
...ry/inc/inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
...ry/inc/inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria() …
```
=> sometime agent don't send name

inc/deploypackage.class.php
When a package is used by a task, a message appears to warn the user.
The link, in this message is incorrect, point to the package form instead of the task form
=> Display a link to the task currently using the package

inc/config.class.php, inc/formatconvert.class.php, inc/inventorycommon.class.php, inc/inventorycomputerlib.class.php, inc/inventorynetworkequipmentlib.class.php, inc/inventoryprinterlib.class.php, phpunit/1_Unit/ComputerTransformationTest.php, phpunit/1_Unit/PrinterTransformationTest.php, phpunit/custom-build.xml
Import simcard and firmwares for network devices and printers.
=> Import simcards, and factorize code

inc/inventorycomputerinventory.class.php, inc/inventorycomputerlib.class.php, inc/inventorynetworkequipmentlib.class.php, inc/inventoryprinterlib.class.php, inc/inventoryruleimport.class.php, inc/inventoryrulelocation.class.php, inc/menu.class.php, inc/toolbox.class.php, phpunit/2_Integration/RuleLocationTest.php, setup.php
add capability to location rule engine to work with snmp asset
=> Location rule engine for snmp asset

inc/communicationnetworkdiscovery.class.php, inc/communicationnetworkinventory.class.php
Recent agents can now inventory storage devices and return a STORAGE type. This PR allows FI plugin to process storage devices as network devices
=> Import storage devices as network devices

inc/agent.class.php
The dropdown link an agent to a computer returns bad values because entity passed to the method is the current entity, instead of the agent's entity
=> Fix dropdown values to link an agent to a computer: was sending a wrong entity ID

inc/formatconvert.class.php, phpunit/2_Integration/ComputerDeviceSimcardTest.php
Import is OK when there are several `FIRMWARES` tags in the XML, but it fails when there is only one.
Same issue exists form SIMCARDS, I've factorized.
Problem is encode/decode XML to convert it to an array. In the first case, we get:
```
$array [
0 => [
'name' => '...',
'version' => '...'
],
1 => [
'name' => '...',
'version' => '...'
]
```
But with the second case:
```
'name' => '...',
'version' => '...'
```
=> Fix stanalone FIRMWARES and SIMCARDS

inc/communicationnetworkinventory.class.php, inc/inventorycommon.class.php, inc/inventorycomputerlib.class.php, inc/inventorynetworkequipmentlib.class.php, inc/inventoryprinterlib.class.php, phpunit/1_Unit/NetworkEquipmentUpdateTest.php, phpunit/1_Unit/PrinterUpdateTest.php, phpunit/2_Integration/DevicesLocksTest.php
Harmonize log behavior at asset creation based on what's done for computers : 
- do not add a log entry during OS creation for a computer
- do not add log entries when manually inserting a XML of SNMP inventory for printers & network devices
=> Do not add entries in the log at asset creation

inc/collectrule.class.php, inc/communicationnetworkdiscovery.class.php, inc/formatconvert.class.php, inc/inventoryrulelocation.class.php
This to conform with the Glpi Statuses that are entities aware where as the FI plugin did not managed this for all the collected fields.
Successfuly tested on the most recent GLPI 9.2 and FI current 9.2 RC1
=> Fix #2416: set an entities_id for collected fields

inc/item.class.php
The very first issue i had was SNMP community not updated due to an incorrect 'id' POSTed to front/switch_info.form.php, see the second commit.
Then i noticed an erroneous call Session::checkRight('plugin_fusioninventory_printer', READ), see the first commit.
=> PluginFusioninventoryItem::showForm() fix

install/update.php
Fixes 2 issues:
- on https://github.com/fusioninventory/fusioninventory-for-glpi/commit/1c2095e9bf#diff-a7f07d4164956baccff73136208ed902R4092 ; I should have used `$iterator2`, not `$iterator` (from parent loop)
- `undefined index $result`
=> Fix iterator migration

inc/deploycheck.class.php, phpunit/1_Unit/Deploy/DeploycheckTest.php
Add a new choice for deployment audit check failure: **`start job now`**
This permits to simply bypass all remaining checks deciding the job still can be started in the case a condition fails.
For example, you can decide to not continue the audit and install a package after checking a registry key exists but you found it doesn't.
This feature will need FusionInventory Agent 2.4.2 (see [PR #564](https://github.com/fusioninventory/fusioninventory-agent/pull/564)).
As agent 2.4.2 use is mandatory, a warning is shown in the audit list.
=> Add 'start job now' support on deploy audit check failure

inc/formatconvert.class.php, phpunit/1_Unit/FormatConvertDataTest.php
When a computer's model dictionary set a manufacturer criterion, it's never provided by fusioninventory.
Ex:
=> provide manufacturer name when importing computer's model in dictionnary

phpunit/0_Install/FusinvInstallTest.php, phpunit/0_Install/mysql/i-0.83+2.1.sql, scripts/cli_install.php
Initial state of plugins in fixtures should not be "ACTIVATED" as normal procedure is to disable plugins prior to begin their upgrade process.
=> Fix plugin states warnings during update tests

hook.php
A new CLI command has been introduced in GLPI 9.5 to install plugins. It uses the `install` hook, so HTML header should not be displayed in CLI context to prevent outputing HTML in CLI context.
See https://github.com/glpi-project/glpi/pull/5862.
=> Fix compatibility with CLI install command from GLPI core

inc/config.class.php, inc/inventoryruleimport.class.php, install/update.php
Option is disabled by default
As monitor serial numbers are very badly handled by manufacturers in EDID block, the one found by the agent is often partly the one visible on the device itself. When people manually adds monitors in its stock, it will of course put as serial number the one found on device itself or on its packaging.
So this option could be enabled when people starts to see duplicated monitors with serial numbers partially different. This won't merge duplicated entries, so people will always have to delete one of the duplicated entries (the one from the dynamic inventory as first choice).
=> Add an option to enable monitor serialnumber partial matching

inc/formatconvert.class.php
This reverts commit 68c6259061787bb68be9553e4b8d362c8f4d072b.
Since PHP 7, `is_array` is faster than casting
```
is_array  :  0.046628952026367
cast, === :  0.18426394462585
Tested 1000000 iterations.
```
=> Revert "Optimize is_array"

inc/agentwakeup.class.php
The 'OR' was wrongly placed during db iterator conversion.
Until this PR is included you can fix the problem by removing your timeslots.
=> fix: wakeupAgents automatic action fails with timeslots

inc/inventoryruleimport.class.php
Fixes `ParseError: syntax error, unexpected 'getItemTypesForRules' (T_STRING), expecting '('` that make tests fails (see https://travis-ci.org/fusioninventory/fusioninventory-for-glpi/jobs/641337057 ).
=> Add missing {

.travis.yml
- drop support of PHP < 7.2
- add support of PHP 7.4
- update dependencies install command params
- remove useless config related to PHP 5.3/5.4
=> Update Travis configuration to matches GLPI 9.5 changes

inc/formatconvert.class.php, install/update.php
Signed-off-by: Stanislas <skita@teclib.com>
When trying to update FusionInventory we have some logs 
```
SQL: INSERT INTO `glpi_items_operatingsystems` (`itemtype`, `items_id`, `operatingsystems_id`, `operatingsystemarchitectures_id`, `operatingsystemversions_id`, `operatingsystemservicepacks_id`, `operatingsystemkernelversions_id`, `operatingsystemeditions_id`, `is_dynamic`, `entities_id`, `is_recursive`, `date_creation`, `date_mod`) VALUES ('Computer', '31839', '2', '1', '0', '1', '21483', '0', '1', NULL, NULL, '2019-12-04 13:35:10', '2019-12-04 13:35:10')
Error: Column 'entities_id' cannot be null
Backtrace :
inc/dbmysql.class.php:866                         
inc/commondbtm.class.php:659                       DBmysql->insert()
inc/commondbtm.class.php:1141 …
```
=> Prevent error on os migration

inc/lock.class.php
Signed-off-by: Stanislas <skita@teclib.com>
Lock icon is displayed only for input but it maybe added to select DOM too
This Pr fix it
=> Correctly display lock icon

hook.php
To prevent this error
when we try to export as CSV (or other) computers list from fusioninventory group
Best regards
=> fix(export): fix call function

front/communication.php
`Toolbox::userErrorHandlerDebug()` has been deprecated in GLPI 9.5 in favor of a new error handler that handles both DEBUG and NORMAL mode.
This new handler is already defined by `includes` scripts.
=> Do not override GLPI error handler

inc/agent.class.php
Fix following error: 
```
[2020-07-09 11:19:39] glpiphplog.CRITICAL: *** Uncaught Exception Error: Class 'DomainItem' not found in /var/www/html/glpi/plugins/fusioninventory/inc/agent.class.php at line 1045
Backtrace :
plugins/fusioninventory/inc/agent.class.php:1084 PluginFusioninventoryAgent->getAgentBaseURLs()
plugins/fusioninventory/inc/agent.class.php:885 PluginFusioninventoryAgent->getAgentStatusURLs()
...s/fusioninventory/inc/agentwakeup.class.php:188 PluginFusioninventoryAgent->getStatus()
inc/crontask.class.php:847 PluginFusioninventoryAgentWakeup::cronWakeupAgents()
front/crontask.form.php:49 CronTask::launch()
```
=> Fix WakeUpAgent cron

hook.php
When we try to load all task job from API, result are partial  because of defaultWhere
This PR fix this
#3007
=> fix(sql): from API do not restrict get all items

setup.php
`classname` attribute has no effect and will produce a warning once https://github.com/glpi-project/glpi/pull/8280 will be merged.
=> Remove invalid class registration attribute
